### ISSUE TITLE
Add Azure Docker Initialization File

### ISSUE THREAD

**Issue by gdufourcq** [Xilinx/Xilinx_Base_Runtime#10]
Hi,
The file "Xilinx_Base_Runtime/utilities/xilinx_docker_setup.sh" does not work with Azure NP10s.
Please create a new file named "Xilinx_Base_Runtime/utilities/xilinx_azure_docker_setup.sh" with following content:
[xilinx_azure_docker_setup.sh.zip](https://github.com/Xilinx/Xilinx_Base_Runtime/files/9065853/xilinx_azure_docker_setup.sh.zip)

I've tested it successfully.
Thanks

**Comment by ethansfng** [comment]
Added
