### ISSUE TITLE
ERROR: Your combination of OS/Cards/XRT Version is not supported. Please reference the list below for supported combinations.

### ISSUE THREAD

**Issue by yewq** [Xilinx/Xilinx_Base_Runtime#12]
I am run `./host_setup.sh -v 2020.1`, which while report `ERROR: Your combination of OS/Cards/XRT Version is not supported. Please reference the list below for supported combinations.`

I am find Alveo U200 is not support for all ${PLATFORM} in https://github.com/Xilinx/Xilinx_Base_Runtime/commit/fa4dd7cd898dca46976721c38efbbd14171be04b.
So I need manual specify `PLATFORM="alveo-u50"` in `host_setup.sh`.

**Comment by yewq** [comment]
I am also find `SHELL_PACKAGE=xilinx-u50-gen3x16-xdma-201920.3-2784799_18.04.deb;` need update to `SHELL_PACKAGE=Xilinx_u50-gen3x16-xdma-201920.3-2784799_18.04_deb.tar.gz;` in conf/spec.txt.

**Comment by ethansfng** [comment]
Hi @yewq, sorry for the late reply, I was out of office.

U200 support has been pulled for every version except the latest version (2022.1 as of writing). You won't be able to setup a u200 card with 2020.1 shell packages with host_setup as the public download links have been removed. If you do have a copy of the 2020.1 u200 shell package somewhere, you can manually install it but not through host_setup.

**Comment by yewq** [comment]
Sorry, I am not express clearly.
I want to setup a u50 card with 2020.1 shell packages. I encountered the problem mentioned above.

So, I am find something:
The variable `${PLATFORM}` is incorrect assignment in function `get_packages()`. It always initial value `alveo-u200`.

**Comment by ethansfng** [comment]
Hi @yewq 

If you want to setup a u50 card with 2020.1 shell package on the command line you will need something like this.
sudo ./host_setup.sh -v 2020.1 -p u50

I think you are probably forgetting to write -p u50 because otherwise you are correct the default value is u200.
