### ISSUE TITLE
Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by ljp0101** [Xilinx/Xilinx_Base_Runtime#13]
Any plans to support soon? Would be nice (for me) as it circumvents some openssl related challenges I'm having that don't present at higher versions. We run f1 containers in a kubernetes cluster on aws.

**Comment by ethansfng** [comment]
Hi @ljp0101,

I can check for you if there are any plans for supporting this. I only develop this tool based on the support from XRT team. There may be some delay to getting back to you due to the holidays.

**Comment by ljp0101** [comment]
FYI, latest XRT supports 22.04.

**Comment by ethansfng** [comment]
Hi @ljp0101,

22.04 is developed and currently being tested.

**Comment by ljp0101** [comment]
Thanks for the update. Looking forward to the release.

**Comment by ljp0101** [comment]
@ethanng72 Working for me. Saved me a bunch of time so thanks.
