### ISSUE TITLE
Docker run script for U55C platform

### ISSUE THREAD

**Issue by junsoo999** [Xilinx/Xilinx_Base_Runtime#14]
Hello, I am using Alveo U55C card with XRT 22.1 / 22.2 version.

I need to run my application in the docker environment, but I think this repo is for older versions.

In XRT 22.1 / 22.2, XRT does not have `xbutil list` command, but `run.sh` contains the old command.

Can you update this repo for U55C device? U55C can only use XRT 22.1 and 22.2...

Otherwise, can you tell me which prefix to bind to the docker container with `--device` options?

There are no `/dev/xfpga/xclmgmt*` but we have `/dev/xfpga/xvc_pri`.

**Comment by ethansfng** [comment]
Hi @junsoo999 ,

Sorry for the late reply, can you attach the output you are getting so I can take a look?

**Comment by ethansfng** [comment]
No update from customer, will reopen if necessary.
