### ISSUE TITLE
When is 2020.2 XRT docker base runtime expected? 

### ISSUE THREAD

**Issue by dzimmyman** [Xilinx/Xilinx_Base_Runtime#3]
We are able to build and run hardware builds using our own docker image we created, but we get the following error trying to run sw and hw emulation: 

Reading appName-xilinx_u250_gen3x16_xdma_2_1_202010_1-sw_emu.xclbin
Loading: 'appName_u250_gen3x16_xdma_2_1_202010_1-sw_emu.xclbin'
ERROR: [SDx-EM 08-0] Failed to connect to device process
The STDIO streams did not close within 10 seconds of the exit event from process '/bin/bash'. This may indicate a child process inherited the STDIO streams and has not yet exited.

**Comment by luciferlee** [comment]
We do have 2020.2 base runtime image dockerfiles. Please check in https://github.com/Xilinx/Xilinx_Base_Runtime/tree/master/Dockerfiles/2020.2. 

You can build your own base runtime images with these dockerfiles.
