### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by kaytabata** [Xilinx/Xilinx_Base_Runtime#4]
Hi,

I have U250 card and executed following command on Ubuntu 2020.4

```sudo ./host_setup.sh -v 2021.1```

Then I got following error message.

```./host_setup.sh: line 343: xilinx-u200-gen3x16-xdma-all_1-3209015.deb_2.tar.gz: command not found```

Do you have work around for this?

**Comment by ethansfng** [comment]
Hi,
This is an issue we are currently working on fixing. Will be updated soon. 
Best,
Ethan

**Comment by kaytabata** [comment]
Thank you for quick response.
I really need this script.
I understand you must be busy, but I'd be grateful if you could fix this.
