### ISSUE TITLE
Ubuntu 20.04 Support for Alveo U280

### ISSUE THREAD

**Issue by linusyukwong** [Xilinx/Xilinx_Base_Runtime#5]
Why is Alveo U280 excluded on support for Vitis 2021.1 / Ubuntu 20.04?

**Comment by ethansfng** [comment]
Hello,

Unfortunately, Alveo U280 cards have never had support for the Ubuntu 20.04 OS. This seems to be an internal decision as 2021.2 XRT also does not support Ubuntu 20.04.

Best,
Ethan
