### ISSUE TITLE
Images pull failure with Docker userns-remap

### ISSUE THREAD

**Issue by ghost** [Xilinx/Xilinx_Base_Runtime#7]
We use Docker userns-remap (https://docs.docker.com/engine/security/userns-remap/) to ensure our container runs less privileged to improve security in our production environment.

When trying to pull any of the 2021.1 or 2021.2 images, I get the following error:
`Failed to register layer: Error processing tar file(exit status 1): Container ID 65673 cannot be mapped to a host ID`

There is no issue with images 2020.2.

The issue occurs always on the same layer when pulling a same image:
```
$ sudo docker pull xilinx/xilinx_runtime_base:alveo-2021.2-ubuntu-20.04

alveo-2021.2-ubuntu-20.04: Pulling from xilinx/xilinx_runtime_base
7b1a6ab2e44d: Pull complete 
7c7ed268ec1b: Pull complete 
e71bc3356696: Pull complete 
475e16d84265: Pull complete 
6c558860c738: Pull complete 
986f87309627: Pull complete 
df1b3905bee8: Extracting [==================================================>]  86.01MB/86.01MB
b6dded541b90: Download complete 
99d63fb6430a: Download complete 
992ff2035fa1: Download complete 
9bc7c05ee31c: Download complete 
1edf11887684: Download complete 
3013114afbcf: Download complete 
627aec4677c1: Download complete 
627f78bf893a: Download complete 
failed to register layer: Error processing tar file(exit status 1): Container ID 65673 cannot be mapped to a host ID
```
This look to correspond to this RUN in the Dockerfile: https://github.com/Xilinx/Xilinx_Base_Runtime/blob/master/Dockerfiles/2021.2/ubuntu-20.04/Dockerfile#L28

The issue look like theses issues:
https://github.com/ovh/the-bastion/issues/24
https://github.com/opensearch-project/opensearch-build/issues/335

Note: on internet we can sometime found an error like this for missing empty disc size, but here I have 20GB of free space.

### Host details

Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-97-generic x86_64)

Docker version:
```Client: Docker Engine - Community
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:45:33 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:42 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

/etc/docker/daemon.json
```json
{
  "icc": false,
  "iptables": true,
  "live-restore": true,
  "log-driver": "journald",
  "log-level": "info",
  "max-concurrent-downloads": 20,
  "max-download-attempts": 20,
  "no-new-privileges": true, 
  "userns-remap": "default", 
  "userland-proxy": false
}
```

/etc/subuid and /etc/subgid
```
ubuntu:100000:65536
dockremap:165536:65536
```

**Comment by xlz-epimor** [comment]
Hi,

Any update on this topic ?

**Comment by ethansfng** [comment]
Hi @xlz-epimor,

This will be fixed in the latest update. This was related to an odd permission setting related to untarring files.

Best,
Ethan

**Comment by ethansfng** [comment]
Updated with -o option in new dockerfiles
