### ISSUE TITLE
Images can be smaller

### ISSUE THREAD

**Issue by ghost** [Xilinx/Xilinx_Base_Runtime#8]
Hello,

XRT images can be smaller. Size for Docker images is important. This speed up the pull step, requires less space on the host when working with a large amount of images, reduce network usage, ...
There are some Good practices explained here: https://docs.docker.com/develop/dev-best-practices/#how-to-keep-your-images-small

You can:
- Reduce the number of "RUN" steps to the minimum to reduce layers counts.
- Remove DEB/RPM/TAG.GZ packages after install.
- Remove shell packages in the same RUN as the one where you downloaded them (This: https://github.com/Xilinx/Xilinx_Base_Runtime/blob/master/Dockerfiles/2021.2/ubuntu-20.04/Dockerfile#L28 does not reduce the size because the files are already in another layer, in fact this increase the size of the image).
- Remove "wget" after use (Or just use curl if already present).
- Clean APT/YUM/DNF cache at the end (Apt example: `apt-get clean && rm -rf /var/lib/apt/lists/*`)

Using multistage build and building with "--squash" can also help.

Also, I noticed that images contains all XRT versions and all shells. I don't see the interest of having other XRT versions when I pull an image with explicitly a XRT version inside the tag. Eventually, you can provides smaller images with only one XRT version (matching the tag) and provides an unversioned tag with everything.
Same for shells, many applications only have a bitstream for one board type. You can provides images for each board, or install none let users install only the shells they need.

**Comment by ethansfng** [comment]
Added new _noshell docker files for latest release and future releases.
Implemented most of these suggestions to minimize layers.
